<?php

namespace App\Enums;

enum RejectionCode: string
{
    case INVALID_QR = 'INVALID_QR';
    case QR_EXPIRED = 'QR_EXPIRED';
    case QR_REVOKED = 'QR_REVOKED';
    case PARTICIPANT_BLOCKED = 'PARTICIPANT_BLOCKED';
    case WRONG_HOTEL = 'WRONG_HOTEL';
    case WRONG_MEETING = 'WRONG_MEETING';
    case SESSION_NOT_OPEN = 'SESSION_NOT_OPEN';
    case SESSION_EXPIRED = 'SESSION_EXPIRED';
    case NO_ENTITLEMENT = 'NO_ENTITLEMENT';
    case ALREADY_REDEEMED = 'ALREADY_REDEEMED';
    case QUOTA_EXHAUSTED = 'QUOTA_EXHAUSTED';
    case DUPLICATE_REQUEST = 'DUPLICATE_REQUEST';
    case MEETING_CANCELLED = 'MEETING_CANCELLED';
    case MEETING_COMPLETED = 'MEETING_COMPLETED';
}
